# These are supported funding model platforms

github: skydoves
patreon: # skydoves
open_collective: # Replace with a single Open Collective username
ko_fi: skydoves
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.buymeacoffee.com/skydoves
